name: Run Telegram Bot

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  schedule:
    - cron: '*/10 * * * *'  # Optional: runs every 10 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.1'  # Set the Python version to 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run the bot
        run: python foodreceipebot.py  # Command to start your bot
